version: '3'

services:
   mongodb:
      image: mongo
      container_name: mongodb
      restart: always
      ports:
       - 27017:27017
      security_opt:
       - seccomp:unconfined
      environment:
       - MONGO_INITDB_ROOT_USERNAME=1
       - MONGO_INITDB_ROOT_PASSWORD=1
     