version: '3'
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 1
      POSTGRES_PASSWORD: 1
    volumes:
      - ./schema-dev.sql:/docker-entrypoint-initdb.d/schema-dev.sql
